app:
  name: "Realtime Chat"
  env: "development" # development | staging | production
  port: 1234
  corsOrigin: "*" # set array in production

db:
  host: "localhost"
  port: 3306
  user: "root"
  pass: "your_password_here"
  name: "chat_service"

redis:
  host: "localhost"
  port: 6379
  pass: "" # empty "" => means password = "default"
  db: 0

jwt:
  secret: "REPLACE_WITH_A_LONG_RANDOM_SECRET"
  expiry: "1h"

kafka:
  enabled: true
  brokers:
    - "localhost:9092"
  clientId: "realtime-chat"

mongo:
  uri: "mongodb://localhost:27017"
  dbName: "chat_logging"
  collection: "logs"

helmet:
  contentSecurityPolicy: false # true in production
  crossOriginEmbedderPolicy: false

rateLimiter:
  windowMs: 60000 # 1 minute
  maxRequests: 100 # per IP

logger:
  enabled: true # enable/disable Mongo logging
  level: "info" # info | warn | error | debug

# NOTE::
# mongodb://admin:password@localhost:27017/audit_logs?authSource=admin
