global:
  scrape_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Node app (Prometheus client on /metrics)
  - job_name: "node_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:4000"] # Your Node port

  # Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  # cAdvisor (docker container metrics)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
